# Generated by Django 5.2.16 on 2026-09-14 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('MEMBERS', 'Members'), ('CUSTOM', 'Custom')], default='MEMBERS', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('uninvited_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_status', models.CharField(blank=True, choices=[('GOING', 'Going'), ('MAYBE', 'Maybe'), ('NOT_GOING', 'Not Going')], max_length=20)),
                ('attendance_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('ATTENDED', 'Attended'), ('ABSENT', 'Absent')], default='UNKNOWN', max_length=20)),
                ('rsvp_updated_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('record_attendance', 'Can record event attendance')],
            },
        ),
        migrations.CreateModel(
            name='EventTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('INVITATION', 'Invitation'), ('VISIBILITY', 'Visibility')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_targets', to='organization.chapter')),
                ('citizenship_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_targets', to='organization.citizenshipclass')),
                ('community_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_targets', to='organization.communitygroup')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='events.event')),
                ('governance_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_targets', to='organization.governancebody')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_targets', to='organization.household')),
                ('household_leadership_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_targets', to='organization.householdleadershiptype')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_targets', to='organization.office')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_targets', to='organization.order')),
                ('order_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_targets', to='organization.orderrank')),
                ('social_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_targets', to='organization.socialrank')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['purpose', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gte', models.F('start_at'))), name='event_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='eventinvitation',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_invitation'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipation',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_participation'),
        ),
    ]
