# Generated by Django 5.2.16 on 2026-08-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventparticipation',
            options={'permissions': [('record_attendance', 'Can record event attendance')]},
        ),
    ]
