# Generated by Django 5.2.16 on 2026-09-14 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('allows_new_citizens', models.BooleanField(default=True)),
                ('is_selectable', models.BooleanField(default=True, verbose_name='Selectable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chapter status',
                'verbose_name_plural': 'Chapter statuses',
            },
        ),
        migrations.CreateModel(
            name='CitizenshipClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_assignable', models.BooleanField(default=True, verbose_name='Assignable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Citizenship class',
                'verbose_name_plural': 'Citizenship classes',
            },
        ),
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_assignable', models.BooleanField(default=True, verbose_name='Assignable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_assignable', models.BooleanField(default=True, verbose_name='Assignable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Governance body',
                'verbose_name_plural': 'Governance bodies',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_assignable', models.BooleanField(default=True, verbose_name='Assignable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdLeadershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_assignable', models.BooleanField(default=True, verbose_name='Assignable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_assignable', models.BooleanField(default=True, verbose_name='Assignable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('uses_ranks', models.BooleanField(default=False)),
                ('is_assignable', models.BooleanField(default=True, verbose_name='Assignable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rank_order', models.PositiveIntegerField(default=0)),
                ('is_assignable', models.BooleanField(default=True, verbose_name='Assignable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_assignable', models.BooleanField(default=True, verbose_name='Assignable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='organization.chapterstatus')),
            ],
        ),
        migrations.CreateModel(
            name='CitizenshipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizenship_records', to='organization.chapter')),
                ('citizenship_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizenship_records', to='organization.citizenshipclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizenship_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='one_current_citizenship_per_user')],
            },
        ),
        migrations.CreateModel(
            name='GovernanceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('governance_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organization.governancebody')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user', 'governance_body'), name='unique_current_governance_membership')],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('community_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organization.communitygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user', 'community_group'), name='unique_current_group_membership')],
            },
        ),
        migrations.CreateModel(
            name='HouseholdLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leadership_records', to='organization.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='household_leadership_records', to=settings.AUTH_USER_MODEL)),
                ('leadership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leadership_records', to='organization.householdleadershiptype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user', 'household', 'leadership_type'), name='unique_current_household_leadership')],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organization.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user', 'household'), name='unique_current_household_membership')],
            },
        ),
        migrations.CreateModel(
            name='InitiateSponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=20)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('initiate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiate_sponsorships', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorships_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('initiate', models.F('sponsor')), _negated=True), name='prevent_self_sponsorship'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('initiate', 'sponsor_type'), name='one_current_sponsor_per_type')],
            },
        ),
        migrations.CreateModel(
            name='OrderMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organization.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_memberships', to=settings.AUTH_USER_MODEL)),
                ('order_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organization.orderrank')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user', 'order'), name='unique_current_order_membership')],
            },
        ),
        migrations.CreateModel(
            name='UserOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_records', to='organization.chapter')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_records', to='organization.office')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user', 'office', 'chapter'), name='unique_current_user_office')],
            },
        ),
        migrations.CreateModel(
            name='UserSocialRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('social_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_records', to='organization.socialrank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_rank_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='one_current_social_rank_per_user')],
            },
        ),
    ]
