# Generated by Django 5.2.16 on 2026-08-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterstatus',
            options={'verbose_name': 'Chapter status', 'verbose_name_plural': 'Chapter statuses'},
        ),
        migrations.AlterModelOptions(
            name='citizenshipclass',
            options={'verbose_name': 'Citizenship class', 'verbose_name_plural': 'Citizenship classes'},
        ),
        migrations.AlterModelOptions(
            name='governancebody',
            options={'verbose_name': 'Governance body', 'verbose_name_plural': 'Governance bodies'},
        ),
    ]
