# Generated by Django 5.2.16 on 2026-08-22 21:35

from django.db import migrations


def seed_organization_definitions(apps, schema_editor):
    CitizenshipClass = apps.get_model("organization", "CitizenshipClass")
    SocialRank = apps.get_model("organization", "SocialRank")
    Office = apps.get_model("organization", "Office")
    ChapterStatus = apps.get_model("organization", "ChapterStatus")
    Chapter = apps.get_model("organization", "Chapter")
    Household = apps.get_model("organization", "Household")
    GovernanceBody = apps.get_model("organization", "GovernanceBody")
    Order = apps.get_model("organization", "Order")
    OrderRank = apps.get_model("organization", "OrderRank")
    HouseholdLeadershipType = apps.get_model(
        "organization",
        "HouseholdLeadershipType",
    )

    chapter_statuses = [
        ("Normal", True),
        ("Honorary", True),
        ("Suspended", False),
        ("Dissolved", False),
    ]

    for name, allows_new_citizens in chapter_statuses:
        ChapterStatus.objects.get_or_create(
            name=name,
            defaults={
                "allows_new_citizens": allows_new_citizens,
                "is_selectable": True,
            },
        )

    normal_status = ChapterStatus.objects.get(name="Normal")
    suspended_status = ChapterStatus.objects.get(name="Suspended")

    chapters = [
        ("Fyr Draca Chapter", normal_status),
        ("Indiana Chapter", suspended_status),
        ("Seattle Chapter", normal_status),
    ]

    for name, status in chapters:
        Chapter.objects.get_or_create(
            name=name,
            defaults={"status": status},
        )

    for name in [
        "Active Citizen",
        "Honorary Citizen",
        "Initiate Citizen",
        "Allied Individual",
    ]:
        CitizenshipClass.objects.get_or_create(name=name)

    for name in [
        "Lysingr",
        "Karl",
        "Thegn",
        "Jarl",
        "Godi",
    ]:
        SocialRank.objects.get_or_create(name=name)

    for name in [
        "Lawspeaker",
        "Hersir",
        "Stallari",
        "Kesserer",
        "Skafari",
        "Skald",
        "Vard",
    ]:
        Office.objects.get_or_create(name=name)

    for name in [
        "House Hvit Hrafn",
        "House Kraken",
        "House Stormhammer",
        "House Three Horns",
        "House Svartur Hrafn",
        "House Silver Zigenare",
    ]:
        Household.objects.get_or_create(name=name)

    GovernanceBody.objects.get_or_create(name="Godi Council")

    HouseholdLeadershipType.objects.get_or_create(
        name="Leading Jarl",
    )

    for name in [
        "Order of Air",
        "Order of Earth",
        "Order of Fire",
        "Order of Water",
    ]:
        Order.objects.get_or_create(
            name=name,
            defaults={"uses_ranks": True},
        )

    for rank_name, rank_order in [
        ("Larling", 1),
        ("Gesallen", 2),
        ("Ledar", 3),
    ]:
        OrderRank.objects.get_or_create(
            name=rank_name,
            defaults={"rank_order": rank_order},
        )

    Order.objects.get_or_create(
        name="Krig Grisar",
        defaults={"uses_ranks": False},
    )


def remove_organization_definitions(apps, schema_editor):
    OrderRank = apps.get_model("organization", "OrderRank")
    Order = apps.get_model("organization", "Order")
    HouseholdLeadershipType = apps.get_model(
        "organization",
        "HouseholdLeadershipType",
    )
    GovernanceBody = apps.get_model("organization", "GovernanceBody")
    Household = apps.get_model("organization", "Household")
    Office = apps.get_model("organization", "Office")
    SocialRank = apps.get_model("organization", "SocialRank")
    CitizenshipClass = apps.get_model("organization", "CitizenshipClass")
    Chapter = apps.get_model("organization", "Chapter")
    ChapterStatus = apps.get_model("organization", "ChapterStatus")

    OrderRank.objects.filter(
        name__in=[
            "Larling",
            "Gesallen",
            "Ledar",
        ]
    ).delete()

    Order.objects.filter(
        name__in=[
            "Order of Air",
            "Order of Earth",
            "Order of Fire",
            "Order of Water",
            "Krig Grisar",
        ]
    ).delete()

    HouseholdLeadershipType.objects.filter(
        name="Leading Jarl",
    ).delete()

    GovernanceBody.objects.filter(
        name="Godi Council",
    ).delete()

    Household.objects.filter(
        name__in=[
            "House Hvit Hrafn",
            "House Kraken",
            "House Stormhammer",
            "House Three Horns",
            "House Svartur Hrafn",
            "House Silver Zigenare",
        ]
    ).delete()

    Office.objects.filter(
        name__in=[
            "Lawspeaker",
            "Hersir",
            "Stallari",
            "Kesserer",
            "Skafari",
            "Skald",
            "Vard",
        ]
    ).delete()

    SocialRank.objects.filter(
        name__in=[
            "Lysingr",
            "Karl",
            "Thegn",
            "Jarl",
            "Godi",
        ]
    ).delete()

    CitizenshipClass.objects.filter(
        name__in=[
            "Active Citizen",
            "Honorary Citizen",
            "Initiate Citizen",
            "Allied Individual",
        ]
    ).delete()

    Chapter.objects.filter(
        name__in=[
            "Fyr Draca Chapter",
            "Indiana Chapter",
            "Seattle Chapter",
        ]
    ).delete()

    ChapterStatus.objects.filter(
        name__in=[
            "Normal",
            "Honorary",
            "Suspended",
            "Dissolved",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_alter_chapterstatus_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            seed_organization_definitions,
            remove_organization_definitions,
        ),
    ]