# Generated by Django 5.2.16 on 2026-08-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_citizenshiprecord_governancemembership_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrank',
            options={'ordering': ['rank_order', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='orderrank',
            name='unique_order_rank_name',
        ),
        migrations.RemoveField(
            model_name='orderrank',
            name='order',
        ),
        migrations.AlterField(
            model_name='orderrank',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
