# Generated by Django 5.2.16 on 2026-08-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='linked_post',
        ),
        migrations.AddField(
            model_name='action',
            name='linked_posts',
            field=models.ManyToManyField(blank=True, related_name='linked_actions', to='community.post'),
        ),
        migrations.AlterField(
            model_name='action',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
