# Generated by Django 5.2.16 on 2026-08-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_remove_action_linked_post_action_linked_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='actionassignment',
            name='unassigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
