# Generated by Django 5.2.16 on 2026-09-14 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'permissions': [('manage_forum_categories', 'Can manage forum categories')],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ForumBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('thread_creation_policy', models.CharField(choices=[('OPEN', 'Open'), ('TARGETED', 'Targeted'), ('STAFF_ONLY', 'Staff only')], default='OPEN', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='community.forumcategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'permissions': [('manage_forum_boards', 'Can manage forum boards')],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ForumPostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='community.forumpost')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ForumPostQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='community.forumpost')),
                ('quoted_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted_by', to='community.forumpost')),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.forumpost')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_post_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_post_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='community.forumboard')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads_created', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_threads', to='community.forumthread')),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('moderate_forum', 'Can moderate the forum'), ('view_archived_forum_content', 'Can view archived forum content'), ('hard_delete_forum_content', 'Can permanently delete forum content')],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.AddField(
            model_name='forumpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.forumthread'),
        ),
        migrations.CreateModel(
            name='ForumDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_type', models.CharField(choices=[('THREAD', 'Thread'), ('POST', 'Post')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('target_data', models.JSONField(blank=True, default=list)),
                ('attachment_links', models.JSONField(blank=True, default=list)),
                ('quoted_post_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_drafts', to='community.forumboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_drafts', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_drafts', to='community.forumthread')),
            ],
        ),
        migrations.CreateModel(
            name='ForumThreadReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='community.forumthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_thread_read_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumThreadSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='community.forumthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_thread_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumThreadTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.chapter')),
                ('citizenship_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.citizenshipclass')),
                ('community_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.communitygroup')),
                ('governance_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.governancebody')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.household')),
                ('household_leadership_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.householdleadershiptype')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.office')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.order')),
                ('order_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.orderrank')),
                ('social_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.socialrank')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='community.forumthread')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForumBoardSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='community.forumboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_board_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'board'), name='unique_forum_board_subscription')],
            },
        ),
        migrations.CreateModel(
            name='ForumBoardTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='community.forumboard')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.chapter')),
                ('citizenship_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.citizenshipclass')),
                ('community_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.communitygroup')),
                ('governance_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.governancebody')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.household')),
                ('household_leadership_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.householdleadershiptype')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.office')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.order')),
                ('order_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.orderrank')),
                ('social_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.socialrank')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), ('citizenship_class__isnull', False), ('social_rank__isnull', False), ('office__isnull', False), ('chapter__isnull', False), ('household__isnull', False), ('governance_body__isnull', False), ('order__isnull', False), ('order_rank__isnull', False), ('community_group__isnull', False), ('household_leadership_type__isnull', False), _connector='OR'), name='community_forumboardtarget_has_selector'), models.CheckConstraint(condition=models.Q(('user__isnull', True), models.Q(('citizenship_class__isnull', True), ('social_rank__isnull', True), ('office__isnull', True), ('chapter__isnull', True), ('household__isnull', True), ('governance_body__isnull', True), ('order__isnull', True), ('order_rank__isnull', True), ('community_group__isnull', True), ('household_leadership_type__isnull', True)), _connector='OR'), name='community_forumboardtarget_user_exclusive')],
            },
        ),
        migrations.CreateModel(
            name='ForumBoardThreadCreationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_creation_targets', to='community.forumboard')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.chapter')),
                ('citizenship_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.citizenshipclass')),
                ('community_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.communitygroup')),
                ('governance_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.governancebody')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.household')),
                ('household_leadership_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.householdleadershiptype')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.office')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.order')),
                ('order_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.orderrank')),
                ('social_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.socialrank')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), ('citizenship_class__isnull', False), ('social_rank__isnull', False), ('office__isnull', False), ('chapter__isnull', False), ('household__isnull', False), ('governance_body__isnull', False), ('order__isnull', False), ('order_rank__isnull', False), ('community_group__isnull', False), ('household_leadership_type__isnull', False), _connector='OR'), name='community_forumboardthreadcreationtarget_has_selector'), models.CheckConstraint(condition=models.Q(('user__isnull', True), models.Q(('citizenship_class__isnull', True), ('social_rank__isnull', True), ('office__isnull', True), ('chapter__isnull', True), ('household__isnull', True), ('governance_body__isnull', True), ('order__isnull', True), ('order_rank__isnull', True), ('community_group__isnull', True), ('household_leadership_type__isnull', True)), _connector='OR'), name='community_forumboardthreadcreationtarget_user_exclusive')],
            },
        ),
        migrations.AddIndex(
            model_name='forumboard',
            index=models.Index(fields=['category', 'display_order', 'name'], name='forum_board_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='forumboard',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_forum_board_name_per_category'),
        ),
        migrations.AddConstraint(
            model_name='forumpostattachment',
            constraint=models.UniqueConstraint(fields=('post', 'url'), name='unique_forum_post_attachment_url'),
        ),
        migrations.AddConstraint(
            model_name='forumpostquote',
            constraint=models.UniqueConstraint(fields=('post', 'quoted_post'), name='unique_forum_post_quote'),
        ),
        migrations.AddConstraint(
            model_name='forumpostquote',
            constraint=models.CheckConstraint(condition=models.Q(('post', models.F('quoted_post')), _negated=True), name='forum_post_cannot_quote_self'),
        ),
        migrations.AddIndex(
            model_name='forumpostreport',
            index=models.Index(fields=['status', 'created_at'], name='forum_report_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='forumpostreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('post', 'reporter'), name='unique_open_forum_post_report'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['board', '-is_pinned', '-last_post_at'], name='forum_thread_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['archived_at'], name='forum_thread_arch_idx'),
        ),
        migrations.AddConstraint(
            model_name='forumthread',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into__isnull', True), models.Q(('merged_into', models.F('id')), _negated=True), _connector='OR'), name='forum_thread_not_merged_into_self'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['thread', 'created_at', 'id'], name='forum_post_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['archived_at'], name='forum_post_arch_idx'),
        ),
        migrations.AddIndex(
            model_name='forumdraft',
            index=models.Index(fields=['user', '-updated_at'], name='forum_draft_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='forumdraft',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('board__isnull', False), ('draft_type', 'THREAD'), ('thread__isnull', True)), models.Q(('board__isnull', True), ('draft_type', 'POST'), ('thread__isnull', False)), _connector='OR'), name='forum_draft_parent_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='forumthreadreadstate',
            constraint=models.UniqueConstraint(fields=('user', 'thread'), name='unique_forum_thread_read_state'),
        ),
        migrations.AddConstraint(
            model_name='forumthreadsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'thread'), name='unique_forum_thread_subscription'),
        ),
        migrations.AddConstraint(
            model_name='forumthreadtarget',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('citizenship_class__isnull', False), ('social_rank__isnull', False), ('office__isnull', False), ('chapter__isnull', False), ('household__isnull', False), ('governance_body__isnull', False), ('order__isnull', False), ('order_rank__isnull', False), ('community_group__isnull', False), ('household_leadership_type__isnull', False), _connector='OR'), name='community_forumthreadtarget_has_selector'),
        ),
        migrations.AddConstraint(
            model_name='forumthreadtarget',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', True), models.Q(('citizenship_class__isnull', True), ('social_rank__isnull', True), ('office__isnull', True), ('chapter__isnull', True), ('household__isnull', True), ('governance_body__isnull', True), ('order__isnull', True), ('order_rank__isnull', True), ('community_group__isnull', True), ('household_leadership_type__isnull', True)), _connector='OR'), name='community_forumthreadtarget_user_exclusive'),
        ),
    ]
