# Generated by Django 5.2.16 on 2026-09-08 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_deleted_at_post_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='previous_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='community.post'),
        ),
    ]
