# Generated by Django 5.2.16 on 2026-08-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('approve_membership', 'Can approve membership')]},
        ),
    ]
