# Generated by Django 5.2.16 on 2026-08-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_prompt_seen',
            field=models.BooleanField(default=False),
        ),
    ]
