# Generated by Django 5.2.16 on 2026-08-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_vote_is_anonymous_voteeligibleuser_has_responded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='push_on_open',
            field=models.BooleanField(default=False),
        ),
    ]
