# Generated by Django 5.2.16 on 2026-08-31 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_vote_push_on_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='push_on_open',
        ),
    ]
