# Generated by Django 5.2.16 on 2026-08-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('BLOCKED', 'Blocked')], default='SENT', max_length=20),
        ),
    ]
