# Generated by Django 5.2.16 on 2026-09-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign'), ('REMOVE', 'Remove'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SUSPEND', 'Suspend'), ('RESTORE', 'Restore'), ('ARCHIVE', 'Archive'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('PIN', 'Pin'), ('UNPIN', 'Unpin'), ('MOVE', 'Move'), ('SPLIT', 'Split'), ('MERGE', 'Merge')], max_length=20),
        ),
    ]
