# Generated by Django 5.2.16 on 2026-08-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='source',
            field=models.CharField(choices=[('ADMIN', 'Django Admin'), ('WEB_APP', 'Web App'), ('ORGANIZATION_SETUP', 'Organization Setup'), ('MEMBER_MANAGEMENT', 'Member Management'), ('IMPORT', 'Import'), ('SYSTEM', 'System'), ('API', 'API')], max_length=30),
        ),
    ]
