# Generated by Django 5.2.16 on 2026-09-14 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('action_push', models.BooleanField(default=True)),
                ('vote_push', models.BooleanField(default=True)),
                ('event_push', models.BooleanField(default=True)),
                ('message_push', models.BooleanField(default=True)),
                ('community_push', models.BooleanField(default=True)),
                ('account_push', models.BooleanField(default=True)),
                ('system_push', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ACTION', 'Action'), ('VOTE', 'Vote'), ('EVENT', 'Event'), ('MESSAGE', 'Message'), ('COMMUNITY', 'Community'), ('ACCOUNT', 'Account'), ('SYSTEM', 'System')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('push_requested', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notification_user_read_idx'), models.Index(fields=['source_type', 'source_id'], name='notification_source_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('p256dh_key', models.TextField()),
                ('auth_key', models.TextField()),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('paused_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'active'], name='push_user_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'endpoint'), name='unique_user_push_endpoint')],
            },
        ),
    ]
