# Generated by Django 5.2.16 on 2026-08-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='push_requested',
            field=models.BooleanField(default=False),
        ),
    ]
