# Generated by Django 5.2.16 on 2026-08-31 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_push_requested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('action_push', models.BooleanField(default=True)),
                ('vote_push', models.BooleanField(default=True)),
                ('event_push', models.BooleanField(default=True)),
                ('message_push', models.BooleanField(default=True)),
                ('community_push', models.BooleanField(default=True)),
                ('account_push', models.BooleanField(default=True)),
                ('system_push', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
