# Generated by Django 5.2.16 on 2026-09-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_pushsubscription_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
